### ISSUE TITLE
Question: Is TLS supported?

### ISSUE THREAD

**Issue by ghost** [raboof/beats-output-http#1]
Quick queries:

1. Which versions of Filebeat this plugin supports? 

2. Is it possible to use TLS to encrypt communication ? A sample config of this would be helpful.

3. I plan to add an authentication header to post requests, do you see any issue in that? 

4. Any stability issues you known of, if TLS is supported I plan to use this in production to ship logs to nginx -> kafka -> logstash -> ES.

Thanks in advance!

**Comment by ghost** [comment]
One more:

5. How does this handle logstash acks? If I remember, filebeat keeps trying till it gets an ack from logstash, in this case it just does a post and moves on right? There are no retrials?

**Comment by raboof** [comment]
Hello @sunny137 - thanks for your questions. This plugin is basically an adaptation of the upstream ElasticSearch plugin, but with the ElasticSearch-specific bits removed. It should support any recent Beats/Filebeat plugin version - if not I'm open to updating the plugin to get up-to-date again. TLS should work (even client certificates IIRC), though I haven't tested this in a while. 

nginx -> kafka -> logstash -> ES seems like a lot of steps, if you're using logstash anyway it might be nice to consider whether you can use that closer to the source as well.

I seem to remember when a POST fails it will be buffered and retried later, but it's been a while.

**Comment by ghost** [comment]
Thanks for quick revert! Let me try this out with filebeat 5.0 and get back to you with my observations. About the pipeline, yes it is a lot of steps but the authentication logic exists in nginx so cant do away with that.

**Comment by sloanqin** [comment]
I get an error when compile it with filebeat5.0 and the latest connbeat.
could you please update the plugin to get up-to-date again?

the error is:
    ./main.go:16:27: cannot use beater.New (type func(*"github.com/raboof/connbeat/vendor/github.com/elastic/beats/libbeat/beat".Beat, *"github.com/raboof/connbeat/vendor/github.com/elastic/beats/libbeat/common".Config) ("github.com/raboof/connbeat/vendor/github.com/elastic/beats/libbeat/beat".Beater, error)) as type "github.com/elastic/beats/libbeat/beat".Creator in argument to "github.com/elastic/beats/libbeat/beat".Run
make: *** [filebeat] Error 2

**Comment by raboof** [comment]
Let's close this issue - feel free to open new ones for specific questions when they're still relevant.

**Comment by raboof** [comment]
(updating to work with newer filebeat versions is in #5)
