### ISSUE TITLE
Integrating with filebeat

### ISSUE THREAD

**Issue by RushinthJohn** [raboof/beats-output-http#2]
Hello could you please tell me exactly how to make this plugin work. I have file beat running on node 1 with the following config
```bash
output:
  http:
    hosts: ["192.168.2.121:80/"]
```
and I have logstash running on node 2 with the following config
```bash
input {
  http {
    host => "192.168.2.122"
    port => 80
  }
}
```
I want filebeat to transfer log files to logstash via HTTP, so could you please run me through how to get it done using your plugin.

**Comment by raboof** [comment]
The best way to send data from a beat to logstash would be to use the logstash output plugin (https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html).

If you want to add this output plugin to a beat anyway, include it as a dependency as described in the README.

**Comment by raboof** [comment]
So to use this output plugin with filebeat you'll have to update filebeat.
